Basic Statistics

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
np.mean(a)

4.0

In [4]:
b=np.array([10,20,34,65,76,87,98,42])
b

array([10, 20, 34, 65, 76, 87, 98, 42])

In [5]:
np.mean(b)

54.0

In [6]:
np.median(b)

53.5

In [7]:
np.median(a)

4.0

In [8]:
a.min()

1

In [9]:
a.max()

7

In [10]:
range_of_a=a.max()-a.min()

In [11]:
range_of_a

6

In [12]:
a.var()

4.0

In [13]:
a.std()

2.0

In [14]:
b

array([10, 20, 34, 65, 76, 87, 98, 42])

In [15]:
b.var()

908.25

In [16]:
b.std()

30.137186331839274

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('student marks.csv')
print(df)

FileNotFoundError: [Errno 2] No such file or directory: 'student marks.csv'

In [4]:
import pandas as pd
import numpy as np

In [5]:
c=np.array([398,654,44,323,432,554,213,645,87])
c

array([398, 654,  44, 323, 432, 554, 213, 645,  87])

In [6]:
c.min()

44

In [7]:
c.max()

654

In [9]:
np.median(c)

398.0

In [10]:
np.mode(c)

AttributeError: module 'numpy' has no attribute 'mode'

In [11]:
np.mean(c)

372.22222222222223

In [12]:
round(c,2)

TypeError: type numpy.ndarray doesn't define __round__ method

In [13]:
round(np.mean(c),2)

372.22

In [3]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv('student_marks.csv')
print(df)

FileNotFoundError: [Errno 2] No such file or directory: 'student_marks.csv'

In [7]:
df=pd.read_csv('student_marks.csv')
print(df)

         Gender         DOB  Maths  Physics  Chemistry  English  Biology  \
John          M  05-04-1988     55       45         56       87       21   
Suresh        M  04-05-1987     75       96         78       64       90   
Ramesh        M  25-05-1989     25       54         89       76       95   
Jessica       F  12-08-1990     78       96         86       63       54   
Jennifer      F  02-09-1989     58       96         78       46       96   
Annu          F  05-04-1988     45       87         52       89       55   
pooja         F  04-05-1987     55       64         61       58       75   
Ritesh        M  25-05-1989     54       76         87       56       25   
Farha         F  12-08-1990     55       63         89       75       78   
Mukesh        M  02-09-1989     96       46         77       83       58   

          Economics  History  Civics  
John             52       89      65  
Suresh           61       58       2  
Ramesh           87       56      74  
Jessica

In [9]:
df['Maths'].mean()

59.6

In [10]:
df['History'].mean()

69.7

In [11]:
df['Civics'].mean()

60.5

In [13]:
df['Physics'].mean()

72.3

In [14]:
df['Chemistry'].mean()

75.3

In [15]:
df['Maths'].median()

55.0

In [16]:
df['English'].median()

69.5

In [17]:
df['Chemistry'].median()

78.0

In [18]:
df['Maths'].std()

19.46050130677807

In [21]:
df['English'].var()
round(df['English'].var(),2)

208.9

In [22]:
df['Economics'].mean()

72.7

In [23]:
df['Economics'].median()

76.0

In [24]:
df['Economics'].var()

214.0111111111111

In [25]:
df['Economics'].std()

14.629118603357862

In [26]:
df

Gender         DOB  Maths  Physics  Chemistry  English  Biology  \
John          M  05-04-1988     55       45         56       87       21   
Suresh        M  04-05-1987     75       96         78       64       90   
Ramesh        M  25-05-1989     25       54         89       76       95   
Jessica       F  12-08-1990     78       96         86       63       54   
Jennifer      F  02-09-1989     58       96         78       46       96   
Annu          F  05-04-1988     45       87         52       89       55   
pooja         F  04-05-1987     55       64         61       58       75   
Ritesh        M  25-05-1989     54       76         87       56       25   
Farha         F  12-08-1990     55       63         89       75       78   
Mukesh        M  02-09-1989     96       46         77       83       58   

          Economics  History  Civics  
John             52       89      65  
Suresh           61       58       2  
Ramesh           87       56      74  
Jessica          89       75      45  
Jennifer         77       83      53  
Annu             89       87      52  
pooja            58       64      61  
Ritesh           56       76      87  
Farha            75       63      89  
Mukesh           83       46      77

In [27]:
df['Biology'].mean()

64.7

In [28]:
df['Biology'].median()

66.5

In [29]:
df['Biology'].var()

728.9000000000001

In [30]:
df['Biology'].std()

26.998148084637215

In [31]:
df['Civics'].mean()

60.5

In [32]:
df['Civics'].median()

63.0

In [33]:
df['Civics'].var()

642.2777777777778

In [34]:
df['Civics'].std()

25.343199833047482

In [35]:
import numpy as np
import pandas as pd

In [36]:
c=np.array([53,53,23,32,43,12,32,76])
print(c)

[53 53 23 32 43 12 32 76]


In [37]:
c.min()

12

In [38]:
c.max()

76

In [39]:
c.var()

355.25

In [40]:
c.std()

18.848076824970764

In [42]:
round(c.std(),2)

18.85